/* Example firmware for HC-SR04 on Nucleo-F439ZI using HAL.
 *
 * Assumptions:
 *  - Generated by STM32CubeMX with TIM3 configured for input capture on PA6
 *    (Channel 1) and GPIO output on PA5 (Trig).
 *  - USART3 configured at 115200 baud for console output.
 *  - SYSCLK at 180 MHz (default Nucleo-F439ZI clock tree).
 */

#include "main.h"
#include <stdio.h>
#include <string.h>

TIM_HandleTypeDef htim3;
UART_HandleTypeDef huart3;

static volatile uint32_t ic_rising = 0U;
static volatile uint32_t ic_falling = 0U;
static volatile uint8_t capture_done = 0U;

static void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_TIM3_Init(void);
static void MX_USART3_UART_Init(void);
static void DWT_Delay_Init(void);
static void delay_us(uint32_t us);
static float HCSR04_Read(void);

int main(void)
{
  HAL_Init();
  SystemClock_Config();

  MX_GPIO_Init();
  MX_TIM3_Init();
  MX_USART3_UART_Init();

  DWT_Delay_Init();

  HAL_TIM_IC_Start_IT(&htim3, TIM_CHANNEL_1);

  char msg[64];

  while (1)
  {
    float distance_cm = HCSR04_Read();

    if (distance_cm >= 0.0f)
    {
      int len = snprintf(msg, sizeof(msg), "Distance: %.2f cm\r\n", distance_cm);
      HAL_UART_Transmit(&huart3, (uint8_t *)msg, len, HAL_MAX_DELAY);
    }
    else
    {
      const char *timeout = "Sensor timeout\r\n";
      HAL_UART_Transmit(&huart3, (uint8_t *)timeout, strlen(timeout), HAL_MAX_DELAY);
    }

    HAL_Delay(100);
  }
}

void HAL_TIM_IC_CaptureCallback(TIM_HandleTypeDef *htim)
{
  if (htim->Instance != TIM3 || htim->Channel != HAL_TIM_ACTIVE_CHANNEL_1)
  {
    return;
  }

  if (!capture_done)
  {
    ic_rising = HAL_TIM_ReadCapturedValue(htim, TIM_CHANNEL_1);
    __HAL_TIM_SET_CAPTUREPOLARITY(htim, TIM_CHANNEL_1, TIM_INPUTCHANNELPOLARITY_FALLING);
    capture_done = 1U;
  }
  else
  {
    ic_falling = HAL_TIM_ReadCapturedValue(htim, TIM_CHANNEL_1);
    capture_done = 2U;
    __HAL_TIM_SET_CAPTUREPOLARITY(htim, TIM_CHANNEL_1, TIM_INPUTCHANNELPOLARITY_RISING);
  }
}

static float HCSR04_Read(void)
{
  capture_done = 0U;
  __HAL_TIM_SET_COUNTER(&htim3, 0U);

  HAL_GPIO_WritePin(HCSR04_TRIG_GPIO_Port, HCSR04_TRIG_Pin, GPIO_PIN_RESET);
  delay_us(2U);
  HAL_GPIO_WritePin(HCSR04_TRIG_GPIO_Port, HCSR04_TRIG_Pin, GPIO_PIN_SET);
  delay_us(10U);
  HAL_GPIO_WritePin(HCSR04_TRIG_GPIO_Port, HCSR04_TRIG_Pin, GPIO_PIN_RESET);

  uint32_t timeout = HAL_GetTick() + 50U;
  while (capture_done < 2U)
  {
    if (HAL_GetTick() > timeout)
    {
      capture_done = 0U;
      return -1.0f;
    }
  }

  uint32_t start = ic_rising;
  uint32_t end = ic_falling;
  uint32_t ticks;

  if (end >= start)
  {
    ticks = end - start;
  }
  else
  {
    ticks = (0xFFFFFFFFUL - start) + end + 1UL;
  }

  const float timer_freq = HAL_RCC_GetPCLK1Freq() * 2.0f;
  const float tick_us = 1e6f / timer_freq * (htim3.Init.Prescaler + 1U);
  float duration_us = ticks * tick_us;

  return (duration_us * 0.0343f) / 2.0f;
}

static void DWT_Delay_Init(void)
{
  CoreDebug->DEMCR |= CoreDebug_DEMCR_TRCENA_Msk;
  DWT->CTRL |= DWT_CTRL_CYCCNTENA_Msk;
}

static void delay_us(uint32_t us)
{
  uint32_t start = DWT->CYCCNT;
  uint32_t cycles = (HAL_RCC_GetHCLKFreq() / 1000000U) * us;
  while ((DWT->CYCCNT - start) < cycles)
  {
  }
}

/* CubeMX generates the functions below. Leave their original content
 * or update the prescaler as needed for 1 MHz timer resolution.
 */
static void MX_TIM3_Init(void)
{
  htim3.Instance = TIM3;
  htim3.Init.Prescaler = (HAL_RCC_GetPCLK1Freq() * 2U / 1000000U) - 1U;
  htim3.Init.CounterMode = TIM_COUNTERMODE_UP;
  htim3.Init.Period = 0xFFFFFFFFUL;
  htim3.Init.ClockDivision = TIM_CLOCKDIVISION_DIV1;
  htim3.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_DISABLE;
  HAL_TIM_Base_Init(&htim3);

  TIM_ClockConfigTypeDef sClockSourceConfig = {0};
  sClockSourceConfig.ClockSource = TIM_CLOCKSOURCE_INTERNAL;
  HAL_TIM_ConfigClockSource(&htim3, &sClockSourceConfig);

  HAL_TIM_IC_Init(&htim3);

  TIM_MasterConfigTypeDef sMasterConfig = {0};
  sMasterConfig.MasterOutputTrigger = TIM_TRGO_RESET;
  sMasterConfig.MasterSlaveMode = TIM_MASTERSLAVEMODE_DISABLE;
  HAL_TIMEx_MasterConfigSynchronization(&htim3, &sMasterConfig);

  TIM_IC_InitTypeDef sConfigIC = {0};
  sConfigIC.ICPolarity = TIM_INPUTCHANNELPOLARITY_RISING;
  sConfigIC.ICSelection = TIM_ICSELECTION_DIRECTTI;
  sConfigIC.ICPrescaler = TIM_ICPSC_DIV1;
  sConfigIC.ICFilter = 0;
  HAL_TIM_IC_ConfigChannel(&htim3, &sConfigIC, TIM_CHANNEL_1);

  HAL_NVIC_SetPriority(TIM3_IRQn, 0, 0);
  HAL_NVIC_EnableIRQ(TIM3_IRQn);
}

void TIM3_IRQHandler(void)
{
  HAL_TIM_IRQHandler(&htim3);
}

/* Placeholder system init stubs. Replace with CubeMX-generated versions. */
static void SystemClock_Config(void) {}
static void MX_GPIO_Init(void) {}
static void MX_USART3_UART_Init(void) {}


