/* Minimal example firmware for the BME280 sensor on Nucleo-F439ZI using HAL.
 *
 * Assumptions:
 *  - Project generated by STM32CubeMX with I2C1 (PB8/PB9) and USART3 enabled.
 *  - USART3 configured at 115200 baud (Virtual COM port via ST-LINK).
 *  - SYSCLK at 180 MHz (default Nucleo-F439ZI clock tree).
 */

#include "main.h"
#include "bme280.h"
#include <stdio.h>
#include <string.h>

I2C_HandleTypeDef hi2c1;
UART_HandleTypeDef huart3;

static void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_I2C1_Init(void);
static void MX_USART3_UART_Init(void);

int main(void)
{
  HAL_Init();
  SystemClock_Config();

  MX_GPIO_Init();
  MX_I2C1_Init();
  MX_USART3_UART_Init();

  BME280_Handle_t bme280 = {
      .i2c = &hi2c1,
      .address = BME280_I2C_ADDR_DEFAULT};

  if (BME280_Init(&bme280) != HAL_OK)
  {
    const char *msg = "BME280 init failed\r\n";
    HAL_UART_Transmit(&huart3, (uint8_t *)msg, strlen(msg), HAL_MAX_DELAY);
    Error_Handler();
  }

  const char *banner = "BME280 ready. Reading measurements...\r\n";
  HAL_UART_Transmit(&huart3, (uint8_t *)banner, strlen(banner), HAL_MAX_DELAY);

  BME280_Measurement_t meas;
  char line[96];

  while (1)
  {
    if (BME280_ReadMeasurements(&bme280, &meas) == HAL_OK)
    {
      int len = snprintf(line, sizeof(line),
                         "Temp: %.2f C, Humidity: %.2f %%RH, Pressure: %.2f hPa\r\n",
                         meas.temperature_c,
                         meas.humidity_rh,
                         meas.pressure_pa / 100.0f);
      HAL_UART_Transmit(&huart3, (uint8_t *)line, len, HAL_MAX_DELAY);
    }
    else
    {
      const char *err = "BME280 read error\r\n";
      HAL_UART_Transmit(&huart3, (uint8_t *)err, strlen(err), HAL_MAX_DELAY);
    }

    HAL_Delay(1000);
  }
}

/* CubeMX will generate concrete implementations for these functions. They are
 * declared here so this example builds even before regeneration. */
static void SystemClock_Config(void)
{
  /* Replace with CubeMX-generated clock tree */
}

static void MX_GPIO_Init(void)
{
  /* Replace with CubeMX-generated GPIO init */
}

static void MX_I2C1_Init(void)
{
  /* Replace with CubeMX-generated I2C1 init */
}

static void MX_USART3_UART_Init(void)
{
  /* Replace with CubeMX-generated USART3 init */
}

void Error_Handler(void)
{
  __disable_irq();
  while (1)
  {
  }
}


